/*
 * Candy Server
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
)

type СandyPrice struct {
	Name        string
	Price       int32
}

type СandyPrices []СandyPrice

var сandyPrices = СandyPrices {
	СandyPrice{
		"CE", 10,
	},
	СandyPrice{
		"AA", 15,
	},
	СandyPrice{
		"NT", 17,
	},
	СandyPrice{
		"DE", 21,
	},
	СandyPrice{
		"YR", 23,
	},
}

func getCandyPrice(name string) (int32, error) {
	for _, candy := range сandyPrices {
		if candy.Name == name {
			return candy.Price, nil
		}
	}
	return 0, fmt.Errorf("Цена для '%s' не найдена", name)
}
